'use client'

import { useState, useCallback } from 'react'
import { useDropzone } from 'react-dropzone'
import { Upload, FileImage, Copy, Check, Loader2, Download } from 'lucide-react'
import toast from 'react-hot-toast'

interface DescriptionResult {
  description: string
  altText: string
  keywords: string[]
  timestamp: string
}

export default function ImageDescriberTool() {
  const [uploadedImage, setUploadedImage] = useState<string | null>(null)
  const [isAnalyzing, setIsAnalyzing] = useState(false)
  const [result, setResult] = useState<DescriptionResult | null>(null)
  const [copiedText, setCopiedText] = useState<string | null>(null)

  const onDrop = useCallback((acceptedFiles: File[]) => {
    const file = acceptedFiles[0]
    if (file) {
      // Check file size (10MB limit)
      if (file.size > 10 * 1024 * 1024) {
        toast.error('File size must be less than 10MB')
        return
      }

      // Check file type
      if (!file.type.startsWith('image/')) {
        toast.error('Please upload a valid image file')
        return
      }

      const reader = new FileReader()
      reader.onload = (e) => {
        setUploadedImage(e.target?.result as string)
        setResult(null) // Clear previous results
      }
      reader.readAsDataURL(file)
    }
  }, [])

  const { getRootProps, getInputProps, isDragActive } = useDropzone({
    onDrop,
    accept: {
      'image/*': ['.jpeg', '.jpg', '.png', '.gif', '.webp']
    },
    multiple: false,
    maxSize: 10 * 1024 * 1024 // 10MB
  })

  const analyzeImage = async () => {
    if (!uploadedImage) {
      toast.error('Please upload an image first')
      return
    }

    setIsAnalyzing(true)
    try {
      const response = await fetch('/api/describe-image', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          image: uploadedImage,
          purpose: 'alt_text_description'
        }),
      })

      if (!response.ok) {
        throw new Error('Failed to analyze image')
      }

      const data = await response.json()
      setResult({
        description: data.description,
        altText: data.altText,
        keywords: data.keywords || [],
        timestamp: new Date().toISOString()
      })
      
      toast.success('Image analyzed successfully!')
    } catch (error) {
      console.error('Error analyzing image:', error)
      toast.error('Failed to analyze image. Please try again.')
    } finally {
      setIsAnalyzing(false)
    }
  }

  const copyToClipboard = async (text: string, type: string) => {
    try {
      await navigator.clipboard.writeText(text)
      setCopiedText(type)
      toast.success(`${type} copied to clipboard!`)
      setTimeout(() => setCopiedText(null), 2000)
    } catch (error) {
      toast.error('Failed to copy to clipboard')
    }
  }

  const downloadAsText = () => {
    if (!result) return

    const content = `Image Description Analysis
Generated: ${new Date(result.timestamp).toLocaleString()}

Full Description:
${result.description}

Alt Text:
${result.altText}

Keywords:
${result.keywords.join(', ')}

Generated by AI Image Describer - https://policesketchmaker.com/ai-image-describer`

    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `image-description-${Date.now()}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
    toast.success('Description downloaded!')
  }

  return (
    <div className="space-y-8">
      {/* Upload Section */}
      <div className="bg-slate-800 rounded-xl p-8">
        <h2 className="text-2xl font-bold mb-6 text-center">
          Upload Image to Describe
        </h2>
        
        <div
          {...getRootProps()}
          className={`border-2 border-dashed rounded-xl p-8 text-center cursor-pointer transition-colors ${
            isDragActive
              ? 'border-blue-400 bg-blue-400/10'
              : 'border-slate-600 hover:border-slate-500'
          }`}
        >
          <input {...getInputProps()} />
          
          {uploadedImage ? (
            <div className="space-y-4">
              <img
                src={uploadedImage}
                alt="Uploaded image"
                className="max-w-full max-h-64 mx-auto rounded-lg"
              />
              <p className="text-slate-300">
                Image uploaded successfully. Click "Describe Image" to analyze.
              </p>
            </div>
          ) : (
            <div className="space-y-4">
              <FileImage className="w-16 h-16 mx-auto text-slate-400" />
              <div>
                <p className="text-lg font-semibold text-slate-200 mb-2">
                  {isDragActive ? 'Drop your image here' : 'Drop image here or click to select'}
                </p>
                <p className="text-slate-400 text-sm">
                  Supports JPG, PNG, WebP, GIF (max 10MB)
                </p>
              </div>
            </div>
          )}
        </div>

        {uploadedImage && (
          <div className="mt-6 text-center">
            <button
              onClick={analyzeImage}
              disabled={isAnalyzing}
              className="inline-flex items-center px-6 py-3 bg-blue-600 hover:bg-blue-700 disabled:bg-slate-600 disabled:cursor-not-allowed text-white font-semibold rounded-lg transition-colors"
            >
              {isAnalyzing ? (
                <>
                  <Loader2 className="w-5 h-5 mr-2 animate-spin" />
                  Analyzing Image...
                </>
              ) : (
                <>
                  <Upload className="w-5 h-5 mr-2" />
                  Describe Image with AI
                </>
              )}
            </button>
          </div>
        )}
      </div>

      {/* Results Section */}
      {result && (
        <div className="bg-slate-800 rounded-xl p-8">
          <div className="flex items-center justify-between mb-6">
            <h2 className="text-2xl font-bold">
              AI Image Description Results
            </h2>
            <button
              onClick={downloadAsText}
              className="inline-flex items-center px-4 py-2 bg-slate-700 hover:bg-slate-600 text-white rounded-lg transition-colors"
            >
              <Download className="w-4 h-4 mr-2" />
              Download
            </button>
          </div>

          <div className="space-y-6">
            {/* Full Description */}
            <div className="bg-slate-900 rounded-lg p-6">
              <div className="flex items-center justify-between mb-3">
                <h3 className="text-lg font-semibold text-blue-400">
                  Full Description
                </h3>
                <button
                  onClick={() => copyToClipboard(result.description, 'Description')}
                  className="inline-flex items-center px-3 py-1 bg-slate-700 hover:bg-slate-600 text-sm rounded transition-colors"
                >
                  {copiedText === 'Description' ? (
                    <Check className="w-4 h-4 mr-1" />
                  ) : (
                    <Copy className="w-4 h-4 mr-1" />
                  )}
                  {copiedText === 'Description' ? 'Copied!' : 'Copy'}
                </button>
              </div>
              <p className="text-slate-200 leading-relaxed">
                {result.description}
              </p>
            </div>

            {/* Alt Text */}
            <div className="bg-slate-900 rounded-lg p-6">
              <div className="flex items-center justify-between mb-3">
                <h3 className="text-lg font-semibold text-blue-400">
                  SEO-Friendly Alt Text
                </h3>
                <button
                  onClick={() => copyToClipboard(result.altText, 'Alt Text')}
                  className="inline-flex items-center px-3 py-1 bg-slate-700 hover:bg-slate-600 text-sm rounded transition-colors"
                >
                  {copiedText === 'Alt Text' ? (
                    <Check className="w-4 h-4 mr-1" />
                  ) : (
                    <Copy className="w-4 h-4 mr-1" />
                  )}
                  {copiedText === 'Alt Text' ? 'Copied!' : 'Copy'}
                </button>
              </div>
              <p className="text-slate-200 leading-relaxed font-mono text-sm bg-slate-800 p-3 rounded">
                {result.altText}
              </p>
            </div>

            {/* Keywords */}
            {result.keywords.length > 0 && (
              <div className="bg-slate-900 rounded-lg p-6">
                <h3 className="text-lg font-semibold text-blue-400 mb-3">
                  Detected Keywords
                </h3>
                <div className="flex flex-wrap gap-2">
                  {result.keywords.map((keyword, index) => (
                    <span
                      key={index}
                      className="px-3 py-1 bg-blue-600/20 text-blue-300 rounded-full text-sm"
                    >
                      {keyword}
                    </span>
                  ))}
                </div>
              </div>
            )}

            {/* Usage Tips */}
            <div className="bg-slate-900 rounded-lg p-6">
              <h3 className="text-lg font-semibold text-blue-400 mb-3">
                How to Use This Description
              </h3>
              <div className="grid md:grid-cols-2 gap-4 text-sm text-slate-300">
                <div>
                  <h4 className="font-semibold text-slate-200 mb-2">For HTML:</h4>
                  <code className="bg-slate-800 p-2 rounded block">
                    &lt;img src="..." alt="{result.altText}" /&gt;
                  </code>
                </div>
                <div>
                  <h4 className="font-semibold text-slate-200 mb-2">For WordPress:</h4>
                  <p>Copy the alt text and paste it into the "Alt Text" field in your media library.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Tips Section */}
      <div className="bg-gradient-to-r from-slate-800 to-slate-700 rounded-xl p-8">
        <h3 className="text-xl font-bold mb-4 text-center">
          💡 Tips for Better Image Descriptions
        </h3>
        <div className="grid md:grid-cols-2 gap-6 text-sm text-slate-300">
          <div>
            <h4 className="font-semibold text-slate-200 mb-2">Best Image Quality:</h4>
            <ul className="space-y-1">
              <li>• Use clear, well-lit images</li>
              <li>• Avoid overly compressed or blurry photos</li>
              <li>• Higher resolution images work better</li>
            </ul>
          </div>
          <div>
            <h4 className="font-semibold text-slate-200 mb-2">For SEO Success:</h4>
            <ul className="space-y-1">
              <li>• Use the generated keywords in your content</li>
              <li>• Include context-relevant descriptions</li>
              <li>• Keep alt text under 125 characters</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  )
} 